version: '3.9'

services:
  server:
    image: 'henrygd/social-image-server'
    container_name: 'social-image-server'
    ports: ['8080:8080']
    # volumes:
    # - ./data:/data # mounts images / db to disk
    environment:
      - REMOTE_URL=ws://chromedp:9222
      - REGEN_KEY=x4hkg3ky8b73 # change this

  browser:
    image: 'chromedp/headless-shell:latest'
    container_name: 'chromedp'
    command: ['--font-render-hinting=none', '--hide-scrollbars']
