services:
  server:
    image: 'henrygd/social-image-server'
    container_name: 'social-image-server'
    init: true
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - ./data:/data # db / images / templates
    # Mounting fonts in the container is optional
    # DejaVu is the only font family provided by the image
    # - /usr/share/fonts:/usr/share/fonts/host:ro # fonts
    environment:
      - REGEN_KEY=x4hkg3ky8b73 # change this
      # - FONT_FAMILY=Inter # override fallback font family
